apiVersion: v1
kind: Service
metadata:
  annotations:
    cloud.google.com/backend-config: '{"default": "iap-backend-config"}'
    cloud.google.com/neg: '{"ingress": true}'
  name: guacamole-app
  labels:
    app: guacamole
    tier: frontend
spec:
  ports:
    - name: guacamole-app
      port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: guacamole
    tier: frontend